/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 59
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 9
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__word = 1,
  sym_frontmatter_language = 2,
  anon_sym_LT = 3,
  anon_sym_GT = 4,
  anon_sym_LT_SLASH = 5,
  sym__tex_tag_name = 6,
  sym__plain_tag_name = 7,
  sym__verbatim_tag_name = 8,
  sym_verbatim_attributes = 9,
  anon_sym_BSLASH_LBRACK = 10,
  anon_sym_BSLASH_RBRACK = 11,
  anon_sym_BSLASH_LPAREN = 12,
  anon_sym_BSLASH_RPAREN = 13,
  anon_sym_DOLLAR = 14,
  anon_sym_DOLLAR_DOLLAR = 15,
  sym_math_content_bracket = 16,
  sym_math_content_paren = 17,
  sym__frontmatter_start = 18,
  sym__frontmatter_end = 19,
  sym__frontmatter_body = 20,
  sym__verbatim_tex_content = 21,
  sym__verbatim_plain_content = 22,
  sym__inline_math_content = 23,
  sym__display_math_content = 24,
  sym__markdown_chunk = 25,
  sym__error_sentinel = 26,
  sym_document = 27,
  sym_frontmatter = 28,
  sym_frontmatter_content = 29,
  sym__block = 30,
  sym_verbatim_environment = 31,
  sym__verbatim_tex = 32,
  sym__verbatim_plain = 33,
  sym_verbatim_tex_open_tag = 34,
  sym_verbatim_plain_open_tag = 35,
  sym_verbatim_close_tag = 36,
  sym_tex_verbatim_body = 37,
  sym_plain_verbatim_body = 38,
  sym_display_math = 39,
  sym_inline_math = 40,
  sym__dollar = 41,
  sym__dollar_dollar = 42,
  sym_math_content_display = 43,
  sym_math_content_inline = 44,
  sym_markdown_chunk = 45,
  aux_sym_document_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__word] = "_word",
  [sym_frontmatter_language] = "frontmatter_language",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [sym__tex_tag_name] = "tag_name",
  [sym__plain_tag_name] = "tag_name",
  [sym__verbatim_tag_name] = "tag_name",
  [sym_verbatim_attributes] = "verbatim_attributes",
  [anon_sym_BSLASH_LBRACK] = "math_delimiter",
  [anon_sym_BSLASH_RBRACK] = "math_delimiter",
  [anon_sym_BSLASH_LPAREN] = "math_delimiter",
  [anon_sym_BSLASH_RPAREN] = "math_delimiter",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_DOLLAR_DOLLAR] = "$$",
  [sym_math_content_bracket] = "math_content_bracket",
  [sym_math_content_paren] = "math_content_paren",
  [sym__frontmatter_start] = "frontmatter_fence",
  [sym__frontmatter_end] = "frontmatter_fence",
  [sym__frontmatter_body] = "_frontmatter_body",
  [sym__verbatim_tex_content] = "_verbatim_tex_content",
  [sym__verbatim_plain_content] = "_verbatim_plain_content",
  [sym__inline_math_content] = "_inline_math_content",
  [sym__display_math_content] = "_display_math_content",
  [sym__markdown_chunk] = "_markdown_chunk",
  [sym__error_sentinel] = "_error_sentinel",
  [sym_document] = "document",
  [sym_frontmatter] = "frontmatter",
  [sym_frontmatter_content] = "frontmatter_content",
  [sym__block] = "_block",
  [sym_verbatim_environment] = "verbatim_environment",
  [sym__verbatim_tex] = "_verbatim_tex",
  [sym__verbatim_plain] = "_verbatim_plain",
  [sym_verbatim_tex_open_tag] = "verbatim_tex_open_tag",
  [sym_verbatim_plain_open_tag] = "verbatim_plain_open_tag",
  [sym_verbatim_close_tag] = "verbatim_close_tag",
  [sym_tex_verbatim_body] = "tex_verbatim_body",
  [sym_plain_verbatim_body] = "plain_verbatim_body",
  [sym_display_math] = "display_math",
  [sym_inline_math] = "inline_math",
  [sym__dollar] = "math_delimiter",
  [sym__dollar_dollar] = "math_delimiter",
  [sym_math_content_display] = "math_content_display",
  [sym_math_content_inline] = "math_content_inline",
  [sym_markdown_chunk] = "markdown_chunk",
  [aux_sym_document_repeat1] = "document_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__word] = sym__word,
  [sym_frontmatter_language] = sym_frontmatter_language,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [sym__tex_tag_name] = sym__tex_tag_name,
  [sym__plain_tag_name] = sym__tex_tag_name,
  [sym__verbatim_tag_name] = sym__tex_tag_name,
  [sym_verbatim_attributes] = sym_verbatim_attributes,
  [anon_sym_BSLASH_LBRACK] = anon_sym_BSLASH_LBRACK,
  [anon_sym_BSLASH_RBRACK] = anon_sym_BSLASH_LBRACK,
  [anon_sym_BSLASH_LPAREN] = anon_sym_BSLASH_LBRACK,
  [anon_sym_BSLASH_RPAREN] = anon_sym_BSLASH_LBRACK,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_DOLLAR_DOLLAR] = anon_sym_DOLLAR_DOLLAR,
  [sym_math_content_bracket] = sym_math_content_bracket,
  [sym_math_content_paren] = sym_math_content_paren,
  [sym__frontmatter_start] = sym__frontmatter_start,
  [sym__frontmatter_end] = sym__frontmatter_start,
  [sym__frontmatter_body] = sym__frontmatter_body,
  [sym__verbatim_tex_content] = sym__verbatim_tex_content,
  [sym__verbatim_plain_content] = sym__verbatim_plain_content,
  [sym__inline_math_content] = sym__inline_math_content,
  [sym__display_math_content] = sym__display_math_content,
  [sym__markdown_chunk] = sym__markdown_chunk,
  [sym__error_sentinel] = sym__error_sentinel,
  [sym_document] = sym_document,
  [sym_frontmatter] = sym_frontmatter,
  [sym_frontmatter_content] = sym_frontmatter_content,
  [sym__block] = sym__block,
  [sym_verbatim_environment] = sym_verbatim_environment,
  [sym__verbatim_tex] = sym__verbatim_tex,
  [sym__verbatim_plain] = sym__verbatim_plain,
  [sym_verbatim_tex_open_tag] = sym_verbatim_tex_open_tag,
  [sym_verbatim_plain_open_tag] = sym_verbatim_plain_open_tag,
  [sym_verbatim_close_tag] = sym_verbatim_close_tag,
  [sym_tex_verbatim_body] = sym_tex_verbatim_body,
  [sym_plain_verbatim_body] = sym_plain_verbatim_body,
  [sym_display_math] = sym_display_math,
  [sym_inline_math] = sym_inline_math,
  [sym__dollar] = anon_sym_BSLASH_LBRACK,
  [sym__dollar_dollar] = anon_sym_BSLASH_LBRACK,
  [sym_math_content_display] = sym_math_content_display,
  [sym_math_content_inline] = sym_math_content_inline,
  [sym_markdown_chunk] = sym_markdown_chunk,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__word] = {
    .visible = false,
    .named = true,
  },
  [sym_frontmatter_language] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym__tex_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__plain_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__verbatim_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_attributes] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH_LBRACK] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH_RBRACK] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH_LPAREN] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH_RPAREN] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_math_content_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_math_content_paren] = {
    .visible = true,
    .named = true,
  },
  [sym__frontmatter_start] = {
    .visible = true,
    .named = true,
  },
  [sym__frontmatter_end] = {
    .visible = true,
    .named = true,
  },
  [sym__frontmatter_body] = {
    .visible = false,
    .named = true,
  },
  [sym__verbatim_tex_content] = {
    .visible = false,
    .named = true,
  },
  [sym__verbatim_plain_content] = {
    .visible = false,
    .named = true,
  },
  [sym__inline_math_content] = {
    .visible = false,
    .named = true,
  },
  [sym__display_math_content] = {
    .visible = false,
    .named = true,
  },
  [sym__markdown_chunk] = {
    .visible = false,
    .named = true,
  },
  [sym__error_sentinel] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter_content] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_verbatim_environment] = {
    .visible = true,
    .named = true,
  },
  [sym__verbatim_tex] = {
    .visible = false,
    .named = true,
  },
  [sym__verbatim_plain] = {
    .visible = false,
    .named = true,
  },
  [sym_verbatim_tex_open_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_plain_open_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_close_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tex_verbatim_body] = {
    .visible = true,
    .named = true,
  },
  [sym_plain_verbatim_body] = {
    .visible = true,
    .named = true,
  },
  [sym_display_math] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_math] = {
    .visible = true,
    .named = true,
  },
  [sym__dollar] = {
    .visible = true,
    .named = true,
  },
  [sym__dollar_dollar] = {
    .visible = true,
    .named = true,
  },
  [sym_math_content_display] = {
    .visible = true,
    .named = true,
  },
  [sym_math_content_inline] = {
    .visible = true,
    .named = true,
  },
  [sym_markdown_chunk] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_attributes = 1,
  field_body = 2,
  field_close = 3,
  field_content = 4,
  field_language = 5,
  field_name = 6,
  field_open = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_attributes] = "attributes",
  [field_body] = "body",
  [field_close] = "close",
  [field_content] = "content",
  [field_language] = "language",
  [field_name] = "name",
  [field_open] = "open",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 2},
  [3] = {.index = 5, .length = 3},
  [4] = {.index = 8, .length = 3},
  [5] = {.index = 11, .length = 1},
  [6] = {.index = 12, .length = 1},
  [7] = {.index = 13, .length = 3},
  [8] = {.index = 16, .length = 4},
  [9] = {.index = 20, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 0, .inherited = true},
    {field_close, 0, .inherited = true},
    {field_open, 0, .inherited = true},
  [3] =
    {field_close, 1},
    {field_open, 0},
  [5] =
    {field_close, 2},
    {field_language, 1},
    {field_open, 0},
  [8] =
    {field_close, 2},
    {field_content, 1},
    {field_open, 0},
  [11] =
    {field_name, 1},
  [12] =
    {field_body, 1},
  [13] =
    {field_body, 1},
    {field_close, 2},
    {field_open, 0},
  [16] =
    {field_close, 3},
    {field_content, 2},
    {field_language, 1},
    {field_open, 0},
  [20] =
    {field_attributes, 2},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 22,
  [31] = 31,
  [32] = 32,
  [33] = 7,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(33);
      ADVANCE_MAP(
        '$', 54,
        '<', 35,
        '>', 36,
        'L', 62,
        'T', 65,
        'V', 67,
        '\\', 3,
        'l', 63,
        't', 68,
        'v', 67,
        '\t', 44,
        '\n', 44,
        '\r', 44,
        ' ', 44,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      if (lookahead != 0) ADVANCE(56);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '$', 53,
        '<', 6,
        'L', 13,
        'T', 17,
        'V', 18,
        'l', 14,
        't', 20,
        'v', 18,
      );
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(51);
      if (lookahead == ')') ADVANCE(52);
      if (lookahead == '[') ADVANCE(49);
      if (lookahead == ']') ADVANCE(50);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(51);
      if (lookahead == ')') ADVANCE(52);
      if (lookahead == '[') ADVANCE(49);
      if (lookahead == ']') ADVANCE(50);
      if (lookahead != 0) ADVANCE(56);
      END_STATE();
    case 4:
      if (lookahead == ')') ADVANCE(52);
      if (lookahead != 0) ADVANCE(58);
      END_STATE();
    case 5:
      if (lookahead == ')') ADVANCE(57);
      if (lookahead == ']') ADVANCE(58);
      if (lookahead != 0) ADVANCE(56);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(37);
      END_STATE();
    case 7:
      if (lookahead == 'T') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == 'X') ADVANCE(38);
      END_STATE();
    case 9:
      if (lookahead == 'Z') ADVANCE(38);
      END_STATE();
    case 10:
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(58);
      END_STATE();
    case 11:
      if (lookahead == '\\') ADVANCE(12);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 12:
      if (lookahead == ']') ADVANCE(50);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 15:
      if (lookahead == 'b') ADVANCE(40);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(8);
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead == 'i') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 22:
      if (lookahead == 'k') ADVANCE(9);
      END_STATE();
    case 23:
      if (lookahead == 'k') ADVANCE(29);
      END_STATE();
    case 24:
      if (lookahead == 'm') ADVANCE(38);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 28:
      if (lookahead == 'x') ADVANCE(38);
      END_STATE();
    case 29:
      if (lookahead == 'z') ADVANCE(38);
      END_STATE();
    case 30:
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(58);
      END_STATE();
    case 31:
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(57);
      END_STATE();
    case 32:
      if (eof) ADVANCE(33);
      if (lookahead == '$') ADVANCE(54);
      if (lookahead == '<') ADVANCE(34);
      if (lookahead == '>') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(48);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__verbatim_tag_name);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__verbatim_tag_name);
      if (lookahead == 'a') ADVANCE(75);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__verbatim_tag_name);
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__verbatim_tag_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_verbatim_attributes);
      if (lookahead == ')') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(46);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_verbatim_attributes);
      if (lookahead == ')') ADVANCE(45);
      if (lookahead == ']') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_verbatim_attributes);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_verbatim_attributes);
      if (lookahead == '\\') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_verbatim_attributes);
      if (lookahead == '\\') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_verbatim_attributes);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(45);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_verbatim_attributes);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_BSLASH_LBRACK);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_BSLASH_RBRACK);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_BSLASH_LPAREN);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_BSLASH_RPAREN);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '$') ADVANCE(55);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_DOLLAR_DOLLAR);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_math_content_bracket);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_math_content_bracket);
      if (lookahead == '\\') ADVANCE(31);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_math_content_paren);
      if (lookahead == '\\') ADVANCE(30);
      if (lookahead != 0) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'T') ADVANCE(66);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'X') ADVANCE(41);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'Z') ADVANCE(41);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Y') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'a') ADVANCE(59);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'a') ADVANCE(76);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'b') ADVANCE(39);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'e') ADVANCE(60);
      if (lookahead == 'i') ADVANCE(71);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'e') ADVANCE(60);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'e') ADVANCE(74);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'e') ADVANCE(77);
      if (lookahead == 'i') ADVANCE(72);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'e') ADVANCE(77);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'i') ADVANCE(73);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'k') ADVANCE(61);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'k') ADVANCE(78);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'm') ADVANCE(41);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'r') ADVANCE(64);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 't') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 't') ADVANCE(69);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'x') ADVANCE(41);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'z') ADVANCE(41);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(79);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'L', 1,
        'T', 2,
        'V', 3,
        'j', 4,
        'l', 5,
        't', 6,
        'v', 7,
        'y', 8,
      );
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(10);
      if (lookahead == 'i') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(15);
      if (lookahead == 'i') ADVANCE(16);
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == 'T') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == 'X') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 'k') ADVANCE(22);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 15:
      if (lookahead == 'x') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'k') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'm') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 'm') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__tex_tag_name);
      END_STATE();
    case 22:
      if (lookahead == 'Z') ADVANCE(21);
      END_STATE();
    case 23:
      if (lookahead == 'b') ADVANCE(31);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 26:
      if (lookahead == 'z') ADVANCE(21);
      END_STATE();
    case 27:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 'b') ADVANCE(34);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 30:
      if (lookahead == 'X') ADVANCE(21);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__plain_tag_name);
      if (lookahead == 'a') ADVANCE(35);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_frontmatter_language);
      END_STATE();
    case 33:
      if (lookahead == 'x') ADVANCE(21);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__plain_tag_name);
      if (lookahead == 'a') ADVANCE(36);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 37:
      if (lookahead == 'i') ADVANCE(39);
      END_STATE();
    case 38:
      if (lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 39:
      if (lookahead == 'm') ADVANCE(41);
      END_STATE();
    case 40:
      if (lookahead == 'm') ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__plain_tag_name);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 32, .external_lex_state = 2},
  [2] = {.lex_state = 32, .external_lex_state = 3},
  [3] = {.lex_state = 32, .external_lex_state = 3},
  [4] = {.lex_state = 32, .external_lex_state = 3},
  [5] = {.lex_state = 32, .external_lex_state = 3},
  [6] = {.lex_state = 32, .external_lex_state = 3},
  [7] = {.lex_state = 32, .external_lex_state = 3},
  [8] = {.lex_state = 32, .external_lex_state = 3},
  [9] = {.lex_state = 32, .external_lex_state = 3},
  [10] = {.lex_state = 32, .external_lex_state = 3},
  [11] = {.lex_state = 32, .external_lex_state = 3},
  [12] = {.lex_state = 32, .external_lex_state = 3},
  [13] = {.lex_state = 32, .external_lex_state = 3},
  [14] = {.lex_state = 32, .external_lex_state = 3},
  [15] = {.lex_state = 32, .external_lex_state = 3},
  [16] = {.lex_state = 32, .external_lex_state = 3},
  [17] = {.lex_state = 32, .external_lex_state = 3},
  [18] = {.lex_state = 32, .external_lex_state = 3},
  [19] = {.lex_state = 32, .external_lex_state = 3},
  [20] = {.lex_state = 32, .external_lex_state = 3},
  [21] = {.lex_state = 32, .external_lex_state = 3},
  [22] = {.lex_state = 32, .external_lex_state = 3},
  [23] = {.lex_state = 32, .external_lex_state = 3},
  [24] = {.lex_state = 1, .external_lex_state = 4},
  [25] = {.lex_state = 32, .external_lex_state = 5},
  [26] = {.lex_state = 1, .external_lex_state = 6},
  [27] = {.lex_state = 1, .external_lex_state = 7},
  [28] = {.lex_state = 32, .external_lex_state = 8},
  [29] = {.lex_state = 0, .external_lex_state = 5},
  [30] = {.lex_state = 1, .external_lex_state = 7},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 32, .external_lex_state = 8},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 32},
  [36] = {.lex_state = 1, .external_lex_state = 4},
  [37] = {.lex_state = 32},
  [38] = {.lex_state = 1, .external_lex_state = 6},
  [39] = {.lex_state = 1, .external_lex_state = 4},
  [40] = {.lex_state = 10},
  [41] = {.lex_state = 32},
  [42] = {.lex_state = 32},
  [43] = {.lex_state = 1, .external_lex_state = 6},
  [44] = {.lex_state = 11},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 32},
  [47] = {.lex_state = 32},
  [48] = {.lex_state = 32},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0, .external_lex_state = 9},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0, .external_lex_state = 9},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 32},
  [56] = {.lex_state = 0, .external_lex_state = 9},
  [57] = {.lex_state = 32},
  [58] = {.lex_state = 32},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__word] = ACTIONS(1),
    [sym_frontmatter_language] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [sym__tex_tag_name] = ACTIONS(1),
    [sym__plain_tag_name] = ACTIONS(1),
    [sym__verbatim_tag_name] = ACTIONS(1),
    [sym_verbatim_attributes] = ACTIONS(1),
    [anon_sym_BSLASH_LBRACK] = ACTIONS(1),
    [anon_sym_BSLASH_RBRACK] = ACTIONS(1),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(1),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_DOLLAR_DOLLAR] = ACTIONS(1),
    [sym_math_content_bracket] = ACTIONS(1),
    [sym_math_content_paren] = ACTIONS(1),
    [sym__frontmatter_start] = ACTIONS(1),
    [sym__frontmatter_end] = ACTIONS(1),
    [sym__frontmatter_body] = ACTIONS(1),
    [sym__verbatim_tex_content] = ACTIONS(1),
    [sym__verbatim_plain_content] = ACTIONS(1),
    [sym__inline_math_content] = ACTIONS(1),
    [sym__display_math_content] = ACTIONS(1),
    [sym__markdown_chunk] = ACTIONS(1),
    [sym__error_sentinel] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(54),
    [sym_frontmatter] = STATE(4),
    [sym__block] = STATE(5),
    [sym_verbatim_environment] = STATE(5),
    [sym__verbatim_tex] = STATE(8),
    [sym__verbatim_plain] = STATE(9),
    [sym_verbatim_tex_open_tag] = STATE(24),
    [sym_verbatim_plain_open_tag] = STATE(26),
    [sym_display_math] = STATE(5),
    [sym_inline_math] = STATE(5),
    [sym__dollar] = STATE(27),
    [sym__dollar_dollar] = STATE(28),
    [sym_markdown_chunk] = STATE(5),
    [aux_sym_document_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT] = ACTIONS(5),
    [anon_sym_BSLASH_LBRACK] = ACTIONS(7),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [anon_sym_DOLLAR_DOLLAR] = ACTIONS(13),
    [sym__frontmatter_start] = ACTIONS(15),
    [sym__markdown_chunk] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_BSLASH_LBRACK,
    ACTIONS(9), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(17), 1,
      sym__markdown_chunk,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      sym__verbatim_tex,
    STATE(9), 1,
      sym__verbatim_plain,
    STATE(24), 1,
      sym_verbatim_tex_open_tag,
    STATE(26), 1,
      sym_verbatim_plain_open_tag,
    STATE(27), 1,
      sym__dollar,
    STATE(28), 1,
      sym__dollar_dollar,
    STATE(3), 6,
      sym__block,
      sym_verbatim_environment,
      sym_display_math,
      sym_inline_math,
      sym_markdown_chunk,
      aux_sym_document_repeat1,
  [48] = 14,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(26), 1,
      anon_sym_BSLASH_LBRACK,
    ACTIONS(29), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(32), 1,
      anon_sym_DOLLAR,
    ACTIONS(35), 1,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(38), 1,
      sym__markdown_chunk,
    STATE(8), 1,
      sym__verbatim_tex,
    STATE(9), 1,
      sym__verbatim_plain,
    STATE(24), 1,
      sym_verbatim_tex_open_tag,
    STATE(26), 1,
      sym_verbatim_plain_open_tag,
    STATE(27), 1,
      sym__dollar,
    STATE(28), 1,
      sym__dollar_dollar,
    STATE(3), 6,
      sym__block,
      sym_verbatim_environment,
      sym_display_math,
      sym_inline_math,
      sym_markdown_chunk,
      aux_sym_document_repeat1,
  [96] = 14,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_BSLASH_LBRACK,
    ACTIONS(9), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(17), 1,
      sym__markdown_chunk,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      sym__verbatim_tex,
    STATE(9), 1,
      sym__verbatim_plain,
    STATE(24), 1,
      sym_verbatim_tex_open_tag,
    STATE(26), 1,
      sym_verbatim_plain_open_tag,
    STATE(27), 1,
      sym__dollar,
    STATE(28), 1,
      sym__dollar_dollar,
    STATE(2), 6,
      sym__block,
      sym_verbatim_environment,
      sym_display_math,
      sym_inline_math,
      sym_markdown_chunk,
      aux_sym_document_repeat1,
  [144] = 14,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(7), 1,
      anon_sym_BSLASH_LBRACK,
    ACTIONS(9), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(17), 1,
      sym__markdown_chunk,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      sym__verbatim_tex,
    STATE(9), 1,
      sym__verbatim_plain,
    STATE(24), 1,
      sym_verbatim_tex_open_tag,
    STATE(26), 1,
      sym_verbatim_plain_open_tag,
    STATE(27), 1,
      sym__dollar,
    STATE(28), 1,
      sym__dollar_dollar,
    STATE(3), 6,
      sym__block,
      sym_verbatim_environment,
      sym_display_math,
      sym_inline_math,
      sym_markdown_chunk,
      aux_sym_document_repeat1,
  [192] = 2,
    ACTIONS(45), 1,
      anon_sym_DOLLAR,
    ACTIONS(43), 6,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [204] = 2,
    ACTIONS(49), 1,
      anon_sym_DOLLAR,
    ACTIONS(47), 6,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [216] = 2,
    ACTIONS(53), 1,
      anon_sym_DOLLAR,
    ACTIONS(51), 6,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [228] = 2,
    ACTIONS(53), 1,
      anon_sym_DOLLAR,
    ACTIONS(51), 6,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [240] = 2,
    ACTIONS(57), 1,
      anon_sym_DOLLAR,
    ACTIONS(55), 6,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [252] = 2,
    ACTIONS(61), 1,
      anon_sym_DOLLAR,
    ACTIONS(59), 6,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [264] = 2,
    ACTIONS(65), 1,
      anon_sym_DOLLAR,
    ACTIONS(63), 6,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [276] = 2,
    ACTIONS(69), 1,
      anon_sym_DOLLAR,
    ACTIONS(67), 6,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [288] = 2,
    ACTIONS(73), 1,
      anon_sym_DOLLAR,
    ACTIONS(71), 6,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [300] = 2,
    ACTIONS(77), 1,
      anon_sym_DOLLAR,
    ACTIONS(75), 6,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [312] = 2,
    ACTIONS(81), 1,
      anon_sym_DOLLAR,
    ACTIONS(79), 6,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [324] = 2,
    ACTIONS(85), 1,
      anon_sym_DOLLAR,
    ACTIONS(83), 6,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [336] = 2,
    ACTIONS(89), 1,
      anon_sym_DOLLAR,
    ACTIONS(87), 6,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [348] = 2,
    ACTIONS(93), 1,
      anon_sym_DOLLAR,
    ACTIONS(91), 6,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [360] = 2,
    ACTIONS(97), 1,
      anon_sym_DOLLAR,
    ACTIONS(95), 6,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [372] = 2,
    ACTIONS(101), 1,
      anon_sym_DOLLAR,
    ACTIONS(99), 6,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [384] = 2,
    ACTIONS(105), 1,
      anon_sym_DOLLAR,
    ACTIONS(103), 6,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [396] = 2,
    ACTIONS(109), 1,
      anon_sym_DOLLAR,
    ACTIONS(107), 6,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [408] = 4,
    ACTIONS(111), 1,
      anon_sym_LT_SLASH,
    ACTIONS(113), 1,
      sym__verbatim_tex_content,
    STATE(6), 1,
      sym_verbatim_close_tag,
    STATE(32), 1,
      sym_tex_verbatim_body,
  [421] = 4,
    ACTIONS(115), 1,
      sym_frontmatter_language,
    ACTIONS(117), 1,
      sym__frontmatter_end,
    ACTIONS(119), 1,
      sym__frontmatter_body,
    STATE(56), 1,
      sym_frontmatter_content,
  [434] = 4,
    ACTIONS(111), 1,
      anon_sym_LT_SLASH,
    ACTIONS(121), 1,
      sym__verbatim_plain_content,
    STATE(13), 1,
      sym_verbatim_close_tag,
    STATE(31), 1,
      sym_plain_verbatim_body,
  [447] = 4,
    ACTIONS(123), 1,
      anon_sym_DOLLAR,
    ACTIONS(125), 1,
      sym__inline_math_content,
    STATE(12), 1,
      sym__dollar,
    STATE(34), 1,
      sym_math_content_inline,
  [460] = 4,
    ACTIONS(127), 1,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(129), 1,
      sym__display_math_content,
    STATE(11), 1,
      sym__dollar_dollar,
    STATE(35), 1,
      sym_math_content_display,
  [473] = 3,
    ACTIONS(119), 1,
      sym__frontmatter_body,
    ACTIONS(131), 1,
      sym__frontmatter_end,
    STATE(51), 1,
      sym_frontmatter_content,
  [483] = 1,
    ACTIONS(103), 2,
      sym__inline_math_content,
      anon_sym_DOLLAR,
  [488] = 2,
    ACTIONS(111), 1,
      anon_sym_LT_SLASH,
    STATE(19), 1,
      sym_verbatim_close_tag,
  [495] = 2,
    ACTIONS(111), 1,
      anon_sym_LT_SLASH,
    STATE(18), 1,
      sym_verbatim_close_tag,
  [502] = 1,
    ACTIONS(47), 2,
      sym__display_math_content,
      anon_sym_DOLLAR_DOLLAR,
  [507] = 2,
    ACTIONS(123), 1,
      anon_sym_DOLLAR,
    STATE(17), 1,
      sym__dollar,
  [514] = 2,
    ACTIONS(127), 1,
      anon_sym_DOLLAR_DOLLAR,
    STATE(16), 1,
      sym__dollar_dollar,
  [521] = 1,
    ACTIONS(133), 2,
      sym__verbatim_tex_content,
      anon_sym_LT_SLASH,
  [526] = 2,
    ACTIONS(135), 1,
      anon_sym_GT,
    ACTIONS(137), 1,
      sym_verbatim_attributes,
  [533] = 1,
    ACTIONS(139), 2,
      sym__verbatim_plain_content,
      anon_sym_LT_SLASH,
  [538] = 1,
    ACTIONS(141), 2,
      sym__verbatim_tex_content,
      anon_sym_LT_SLASH,
  [543] = 2,
    ACTIONS(143), 1,
      anon_sym_BSLASH_RPAREN,
    ACTIONS(145), 1,
      sym_math_content_paren,
  [550] = 2,
    ACTIONS(147), 1,
      sym__tex_tag_name,
    ACTIONS(149), 1,
      sym__plain_tag_name,
  [557] = 2,
    ACTIONS(151), 1,
      anon_sym_GT,
    ACTIONS(153), 1,
      sym_verbatim_attributes,
  [564] = 1,
    ACTIONS(155), 2,
      sym__verbatim_plain_content,
      anon_sym_LT_SLASH,
  [569] = 2,
    ACTIONS(157), 1,
      anon_sym_BSLASH_RBRACK,
    ACTIONS(159), 1,
      sym_math_content_bracket,
  [576] = 1,
    ACTIONS(161), 1,
      anon_sym_DOLLAR,
  [580] = 1,
    ACTIONS(163), 1,
      anon_sym_BSLASH_RPAREN,
  [584] = 1,
    ACTIONS(165), 1,
      anon_sym_BSLASH_RBRACK,
  [588] = 1,
    ACTIONS(167), 1,
      anon_sym_DOLLAR_DOLLAR,
  [592] = 1,
    ACTIONS(169), 1,
      anon_sym_LT_SLASH,
  [596] = 1,
    ACTIONS(171), 1,
      anon_sym_LT_SLASH,
  [600] = 1,
    ACTIONS(173), 1,
      sym__frontmatter_end,
  [604] = 1,
    ACTIONS(175), 1,
      sym__verbatim_tag_name,
  [608] = 1,
    ACTIONS(177), 1,
      sym__frontmatter_end,
  [612] = 1,
    ACTIONS(179), 1,
      ts_builtin_sym_end,
  [616] = 1,
    ACTIONS(181), 1,
      anon_sym_GT,
  [620] = 1,
    ACTIONS(183), 1,
      sym__frontmatter_end,
  [624] = 1,
    ACTIONS(185), 1,
      anon_sym_GT,
  [628] = 1,
    ACTIONS(187), 1,
      anon_sym_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 96,
  [SMALL_STATE(5)] = 144,
  [SMALL_STATE(6)] = 192,
  [SMALL_STATE(7)] = 204,
  [SMALL_STATE(8)] = 216,
  [SMALL_STATE(9)] = 228,
  [SMALL_STATE(10)] = 240,
  [SMALL_STATE(11)] = 252,
  [SMALL_STATE(12)] = 264,
  [SMALL_STATE(13)] = 276,
  [SMALL_STATE(14)] = 288,
  [SMALL_STATE(15)] = 300,
  [SMALL_STATE(16)] = 312,
  [SMALL_STATE(17)] = 324,
  [SMALL_STATE(18)] = 336,
  [SMALL_STATE(19)] = 348,
  [SMALL_STATE(20)] = 360,
  [SMALL_STATE(21)] = 372,
  [SMALL_STATE(22)] = 384,
  [SMALL_STATE(23)] = 396,
  [SMALL_STATE(24)] = 408,
  [SMALL_STATE(25)] = 421,
  [SMALL_STATE(26)] = 434,
  [SMALL_STATE(27)] = 447,
  [SMALL_STATE(28)] = 460,
  [SMALL_STATE(29)] = 473,
  [SMALL_STATE(30)] = 483,
  [SMALL_STATE(31)] = 488,
  [SMALL_STATE(32)] = 495,
  [SMALL_STATE(33)] = 502,
  [SMALL_STATE(34)] = 507,
  [SMALL_STATE(35)] = 514,
  [SMALL_STATE(36)] = 521,
  [SMALL_STATE(37)] = 526,
  [SMALL_STATE(38)] = 533,
  [SMALL_STATE(39)] = 538,
  [SMALL_STATE(40)] = 543,
  [SMALL_STATE(41)] = 550,
  [SMALL_STATE(42)] = 557,
  [SMALL_STATE(43)] = 564,
  [SMALL_STATE(44)] = 569,
  [SMALL_STATE(45)] = 576,
  [SMALL_STATE(46)] = 580,
  [SMALL_STATE(47)] = 584,
  [SMALL_STATE(48)] = 588,
  [SMALL_STATE(49)] = 592,
  [SMALL_STATE(50)] = 596,
  [SMALL_STATE(51)] = 600,
  [SMALL_STATE(52)] = 604,
  [SMALL_STATE(53)] = 608,
  [SMALL_STATE(54)] = 612,
  [SMALL_STATE(55)] = 616,
  [SMALL_STATE(56)] = 620,
  [SMALL_STATE(57)] = 624,
  [SMALL_STATE(58)] = 628,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__verbatim_tex, 2, 0, 2),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__verbatim_tex, 2, 0, 2),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__dollar_dollar, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__dollar_dollar, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_environment, 1, 0, 1),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_environment, 1, 0, 1),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 2, 0, 2),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_frontmatter, 2, 0, 2),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_display_math, 2, 2, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_display_math, 2, 2, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_math, 2, 1, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_math, 2, 1, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__verbatim_plain, 2, 0, 2),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__verbatim_plain, 2, 0, 2),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 3, 0, 3),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_frontmatter, 3, 0, 3),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 3, 0, 4),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_frontmatter, 3, 0, 4),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_display_math, 3, 2, 6),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_display_math, 3, 2, 6),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_math, 3, 1, 6),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_math, 3, 1, 6),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__verbatim_tex, 3, 0, 7),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__verbatim_tex, 3, 0, 7),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__verbatim_plain, 3, 0, 7),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__verbatim_plain, 3, 0, 7),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 4, 0, 8),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_frontmatter, 4, 0, 8),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_close_tag, 3, 0, 5),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_close_tag, 3, 0, 5),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__dollar, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__dollar, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_chunk, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_chunk, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_tex_open_tag, 3, 0, 5),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_plain_open_tag, 3, 0, 5),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_tex_open_tag, 4, 0, 9),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_plain_open_tag, 4, 0, 9),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_content_inline, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_content_display, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plain_verbatim_body, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tex_verbatim_body, 1, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter_content, 1, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__frontmatter_start = 0,
  ts_external_token__frontmatter_end = 1,
  ts_external_token__frontmatter_body = 2,
  ts_external_token__verbatim_tex_content = 3,
  ts_external_token__verbatim_plain_content = 4,
  ts_external_token__inline_math_content = 5,
  ts_external_token__display_math_content = 6,
  ts_external_token__markdown_chunk = 7,
  ts_external_token__error_sentinel = 8,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__frontmatter_start] = sym__frontmatter_start,
  [ts_external_token__frontmatter_end] = sym__frontmatter_end,
  [ts_external_token__frontmatter_body] = sym__frontmatter_body,
  [ts_external_token__verbatim_tex_content] = sym__verbatim_tex_content,
  [ts_external_token__verbatim_plain_content] = sym__verbatim_plain_content,
  [ts_external_token__inline_math_content] = sym__inline_math_content,
  [ts_external_token__display_math_content] = sym__display_math_content,
  [ts_external_token__markdown_chunk] = sym__markdown_chunk,
  [ts_external_token__error_sentinel] = sym__error_sentinel,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__frontmatter_start] = true,
    [ts_external_token__frontmatter_end] = true,
    [ts_external_token__frontmatter_body] = true,
    [ts_external_token__verbatim_tex_content] = true,
    [ts_external_token__verbatim_plain_content] = true,
    [ts_external_token__inline_math_content] = true,
    [ts_external_token__display_math_content] = true,
    [ts_external_token__markdown_chunk] = true,
    [ts_external_token__error_sentinel] = true,
  },
  [2] = {
    [ts_external_token__frontmatter_start] = true,
    [ts_external_token__markdown_chunk] = true,
  },
  [3] = {
    [ts_external_token__markdown_chunk] = true,
  },
  [4] = {
    [ts_external_token__verbatim_tex_content] = true,
  },
  [5] = {
    [ts_external_token__frontmatter_end] = true,
    [ts_external_token__frontmatter_body] = true,
  },
  [6] = {
    [ts_external_token__verbatim_plain_content] = true,
  },
  [7] = {
    [ts_external_token__inline_math_content] = true,
  },
  [8] = {
    [ts_external_token__display_math_content] = true,
  },
  [9] = {
    [ts_external_token__frontmatter_end] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_sveltex_external_scanner_create(void);
void tree_sitter_sveltex_external_scanner_destroy(void *);
bool tree_sitter_sveltex_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_sveltex_external_scanner_serialize(void *, char *);
void tree_sitter_sveltex_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sveltex(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__word,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_sveltex_external_scanner_create,
      tree_sitter_sveltex_external_scanner_destroy,
      tree_sitter_sveltex_external_scanner_scan,
      tree_sitter_sveltex_external_scanner_serialize,
      tree_sitter_sveltex_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "sveltex",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
