/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 64
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 10
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__word = 1,
  sym_frontmatter_language = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_LT = 5,
  anon_sym_GT = 6,
  anon_sym_LT_SLASH = 7,
  sym__tex_tag_name = 8,
  sym__plain_tag_name = 9,
  sym__verbatim_tag_name = 10,
  sym_verbatim_attributes = 11,
  anon_sym_BSLASH_LBRACK = 12,
  anon_sym_BSLASH_RBRACK = 13,
  anon_sym_BSLASH_LPAREN = 14,
  anon_sym_BSLASH_RPAREN = 15,
  anon_sym_DOLLAR = 16,
  anon_sym_DOLLAR_DOLLAR = 17,
  sym_math_content_bracket = 18,
  sym_math_content_paren = 19,
  sym__frontmatter_start = 20,
  sym__frontmatter_end = 21,
  sym__frontmatter_body = 22,
  sym__verbatim_tex_content = 23,
  sym__verbatim_plain_content = 24,
  sym__inline_math_content = 25,
  sym__display_math_content = 26,
  sym__markdown_chunk = 27,
  sym__svelte_expression_body = 28,
  sym__error_sentinel = 29,
  sym_document = 30,
  sym_frontmatter = 31,
  sym_frontmatter_content = 32,
  sym__block = 33,
  sym_svelte_expression = 34,
  sym_svelte_expression_body = 35,
  sym_verbatim_environment = 36,
  sym__verbatim_tex = 37,
  sym__verbatim_plain = 38,
  sym_verbatim_tex_open_tag = 39,
  sym_verbatim_plain_open_tag = 40,
  sym_verbatim_close_tag = 41,
  sym_tex_verbatim_body = 42,
  sym_plain_verbatim_body = 43,
  sym_display_math = 44,
  sym_inline_math = 45,
  sym__dollar = 46,
  sym__dollar_dollar = 47,
  sym_math_content_display = 48,
  sym_math_content_inline = 49,
  sym_markdown_chunk = 50,
  aux_sym_document_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__word] = "_word",
  [sym_frontmatter_language] = "frontmatter_language",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [sym__tex_tag_name] = "tag_name",
  [sym__plain_tag_name] = "tag_name",
  [sym__verbatim_tag_name] = "tag_name",
  [sym_verbatim_attributes] = "verbatim_attributes",
  [anon_sym_BSLASH_LBRACK] = "math_delimiter",
  [anon_sym_BSLASH_RBRACK] = "math_delimiter",
  [anon_sym_BSLASH_LPAREN] = "math_delimiter",
  [anon_sym_BSLASH_RPAREN] = "math_delimiter",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_DOLLAR_DOLLAR] = "$$",
  [sym_math_content_bracket] = "math_content_bracket",
  [sym_math_content_paren] = "math_content_paren",
  [sym__frontmatter_start] = "frontmatter_fence",
  [sym__frontmatter_end] = "frontmatter_fence",
  [sym__frontmatter_body] = "_frontmatter_body",
  [sym__verbatim_tex_content] = "_verbatim_tex_content",
  [sym__verbatim_plain_content] = "_verbatim_plain_content",
  [sym__inline_math_content] = "_inline_math_content",
  [sym__display_math_content] = "_display_math_content",
  [sym__markdown_chunk] = "_markdown_chunk",
  [sym__svelte_expression_body] = "_svelte_expression_body",
  [sym__error_sentinel] = "_error_sentinel",
  [sym_document] = "document",
  [sym_frontmatter] = "frontmatter",
  [sym_frontmatter_content] = "frontmatter_content",
  [sym__block] = "_block",
  [sym_svelte_expression] = "svelte_expression",
  [sym_svelte_expression_body] = "svelte_expression_body",
  [sym_verbatim_environment] = "verbatim_environment",
  [sym__verbatim_tex] = "_verbatim_tex",
  [sym__verbatim_plain] = "_verbatim_plain",
  [sym_verbatim_tex_open_tag] = "verbatim_tex_open_tag",
  [sym_verbatim_plain_open_tag] = "verbatim_plain_open_tag",
  [sym_verbatim_close_tag] = "verbatim_close_tag",
  [sym_tex_verbatim_body] = "tex_verbatim_body",
  [sym_plain_verbatim_body] = "plain_verbatim_body",
  [sym_display_math] = "display_math",
  [sym_inline_math] = "inline_math",
  [sym__dollar] = "math_delimiter",
  [sym__dollar_dollar] = "math_delimiter",
  [sym_math_content_display] = "math_content_display",
  [sym_math_content_inline] = "math_content_inline",
  [sym_markdown_chunk] = "markdown_chunk",
  [aux_sym_document_repeat1] = "document_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__word] = sym__word,
  [sym_frontmatter_language] = sym_frontmatter_language,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [sym__tex_tag_name] = sym__tex_tag_name,
  [sym__plain_tag_name] = sym__tex_tag_name,
  [sym__verbatim_tag_name] = sym__tex_tag_name,
  [sym_verbatim_attributes] = sym_verbatim_attributes,
  [anon_sym_BSLASH_LBRACK] = anon_sym_BSLASH_LBRACK,
  [anon_sym_BSLASH_RBRACK] = anon_sym_BSLASH_LBRACK,
  [anon_sym_BSLASH_LPAREN] = anon_sym_BSLASH_LBRACK,
  [anon_sym_BSLASH_RPAREN] = anon_sym_BSLASH_LBRACK,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_DOLLAR_DOLLAR] = anon_sym_DOLLAR_DOLLAR,
  [sym_math_content_bracket] = sym_math_content_bracket,
  [sym_math_content_paren] = sym_math_content_paren,
  [sym__frontmatter_start] = sym__frontmatter_start,
  [sym__frontmatter_end] = sym__frontmatter_start,
  [sym__frontmatter_body] = sym__frontmatter_body,
  [sym__verbatim_tex_content] = sym__verbatim_tex_content,
  [sym__verbatim_plain_content] = sym__verbatim_plain_content,
  [sym__inline_math_content] = sym__inline_math_content,
  [sym__display_math_content] = sym__display_math_content,
  [sym__markdown_chunk] = sym__markdown_chunk,
  [sym__svelte_expression_body] = sym__svelte_expression_body,
  [sym__error_sentinel] = sym__error_sentinel,
  [sym_document] = sym_document,
  [sym_frontmatter] = sym_frontmatter,
  [sym_frontmatter_content] = sym_frontmatter_content,
  [sym__block] = sym__block,
  [sym_svelte_expression] = sym_svelte_expression,
  [sym_svelte_expression_body] = sym_svelte_expression_body,
  [sym_verbatim_environment] = sym_verbatim_environment,
  [sym__verbatim_tex] = sym__verbatim_tex,
  [sym__verbatim_plain] = sym__verbatim_plain,
  [sym_verbatim_tex_open_tag] = sym_verbatim_tex_open_tag,
  [sym_verbatim_plain_open_tag] = sym_verbatim_plain_open_tag,
  [sym_verbatim_close_tag] = sym_verbatim_close_tag,
  [sym_tex_verbatim_body] = sym_tex_verbatim_body,
  [sym_plain_verbatim_body] = sym_plain_verbatim_body,
  [sym_display_math] = sym_display_math,
  [sym_inline_math] = sym_inline_math,
  [sym__dollar] = anon_sym_BSLASH_LBRACK,
  [sym__dollar_dollar] = anon_sym_BSLASH_LBRACK,
  [sym_math_content_display] = sym_math_content_display,
  [sym_math_content_inline] = sym_math_content_inline,
  [sym_markdown_chunk] = sym_markdown_chunk,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__word] = {
    .visible = false,
    .named = true,
  },
  [sym_frontmatter_language] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym__tex_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__plain_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__verbatim_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_attributes] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH_LBRACK] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH_RBRACK] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH_LPAREN] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH_RPAREN] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_math_content_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_math_content_paren] = {
    .visible = true,
    .named = true,
  },
  [sym__frontmatter_start] = {
    .visible = true,
    .named = true,
  },
  [sym__frontmatter_end] = {
    .visible = true,
    .named = true,
  },
  [sym__frontmatter_body] = {
    .visible = false,
    .named = true,
  },
  [sym__verbatim_tex_content] = {
    .visible = false,
    .named = true,
  },
  [sym__verbatim_plain_content] = {
    .visible = false,
    .named = true,
  },
  [sym__inline_math_content] = {
    .visible = false,
    .named = true,
  },
  [sym__display_math_content] = {
    .visible = false,
    .named = true,
  },
  [sym__markdown_chunk] = {
    .visible = false,
    .named = true,
  },
  [sym__svelte_expression_body] = {
    .visible = false,
    .named = true,
  },
  [sym__error_sentinel] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter_content] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_svelte_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_svelte_expression_body] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_environment] = {
    .visible = true,
    .named = true,
  },
  [sym__verbatim_tex] = {
    .visible = false,
    .named = true,
  },
  [sym__verbatim_plain] = {
    .visible = false,
    .named = true,
  },
  [sym_verbatim_tex_open_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_plain_open_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_close_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tex_verbatim_body] = {
    .visible = true,
    .named = true,
  },
  [sym_plain_verbatim_body] = {
    .visible = true,
    .named = true,
  },
  [sym_display_math] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_math] = {
    .visible = true,
    .named = true,
  },
  [sym__dollar] = {
    .visible = true,
    .named = true,
  },
  [sym__dollar_dollar] = {
    .visible = true,
    .named = true,
  },
  [sym_math_content_display] = {
    .visible = true,
    .named = true,
  },
  [sym_math_content_inline] = {
    .visible = true,
    .named = true,
  },
  [sym_markdown_chunk] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_attributes = 1,
  field_body = 2,
  field_close = 3,
  field_content = 4,
  field_language = 5,
  field_name = 6,
  field_open = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_attributes] = "attributes",
  [field_body] = "body",
  [field_close] = "close",
  [field_content] = "content",
  [field_language] = "language",
  [field_name] = "name",
  [field_open] = "open",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 2},
  [3] = {.index = 5, .length = 3},
  [4] = {.index = 8, .length = 3},
  [5] = {.index = 11, .length = 1},
  [6] = {.index = 12, .length = 1},
  [7] = {.index = 13, .length = 3},
  [8] = {.index = 16, .length = 4},
  [9] = {.index = 20, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 0, .inherited = true},
    {field_close, 0, .inherited = true},
    {field_open, 0, .inherited = true},
  [3] =
    {field_close, 1},
    {field_open, 0},
  [5] =
    {field_close, 2},
    {field_language, 1},
    {field_open, 0},
  [8] =
    {field_close, 2},
    {field_content, 1},
    {field_open, 0},
  [11] =
    {field_body, 1},
  [12] =
    {field_name, 1},
  [13] =
    {field_body, 1},
    {field_close, 2},
    {field_open, 0},
  [16] =
    {field_close, 3},
    {field_content, 2},
    {field_language, 1},
    {field_open, 0},
  [20] =
    {field_attributes, 2},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 24,
  [46] = 46,
  [47] = 25,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(33);
      ADVANCE_MAP(
        '$', 56,
        '<', 37,
        '>', 38,
        'L', 64,
        'T', 67,
        'V', 69,
        '\\', 3,
        'l', 65,
        't', 70,
        'v', 69,
        '{', 34,
        '}', 35,
        '\t', 46,
        '\n', 46,
        '\r', 46,
        ' ', 46,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      if (lookahead != 0) ADVANCE(58);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '$', 55,
        '<', 6,
        'L', 13,
        'T', 17,
        'V', 18,
        'l', 14,
        't', 20,
        'v', 18,
      );
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(53);
      if (lookahead == ')') ADVANCE(54);
      if (lookahead == '[') ADVANCE(51);
      if (lookahead == ']') ADVANCE(52);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(53);
      if (lookahead == ')') ADVANCE(54);
      if (lookahead == '[') ADVANCE(51);
      if (lookahead == ']') ADVANCE(52);
      if (lookahead != 0) ADVANCE(58);
      END_STATE();
    case 4:
      if (lookahead == ')') ADVANCE(54);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 5:
      if (lookahead == ')') ADVANCE(59);
      if (lookahead == ']') ADVANCE(60);
      if (lookahead != 0) ADVANCE(58);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(39);
      END_STATE();
    case 7:
      if (lookahead == 'T') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == 'X') ADVANCE(40);
      END_STATE();
    case 9:
      if (lookahead == 'Z') ADVANCE(40);
      END_STATE();
    case 10:
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 11:
      if (lookahead == '\\') ADVANCE(12);
      if (lookahead != 0) ADVANCE(59);
      END_STATE();
    case 12:
      if (lookahead == ']') ADVANCE(52);
      if (lookahead != 0) ADVANCE(59);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 15:
      if (lookahead == 'b') ADVANCE(42);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(8);
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead == 'i') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 22:
      if (lookahead == 'k') ADVANCE(9);
      END_STATE();
    case 23:
      if (lookahead == 'k') ADVANCE(29);
      END_STATE();
    case 24:
      if (lookahead == 'm') ADVANCE(40);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 28:
      if (lookahead == 'x') ADVANCE(40);
      END_STATE();
    case 29:
      if (lookahead == 'z') ADVANCE(40);
      END_STATE();
    case 30:
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(60);
      END_STATE();
    case 31:
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(59);
      END_STATE();
    case 32:
      if (eof) ADVANCE(33);
      ADVANCE_MAP(
        '$', 56,
        '<', 36,
        '>', 38,
        '\\', 2,
        '{', 34,
        '}', 35,
        '\t', 50,
        '\n', 50,
        '\r', 50,
        ' ', 50,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__verbatim_tag_name);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__verbatim_tag_name);
      if (lookahead == 'a') ADVANCE(77);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__verbatim_tag_name);
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__verbatim_tag_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_verbatim_attributes);
      if (lookahead == ')') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(48);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_verbatim_attributes);
      if (lookahead == ')') ADVANCE(47);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_verbatim_attributes);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_verbatim_attributes);
      if (lookahead == '\\') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_verbatim_attributes);
      if (lookahead == '\\') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_verbatim_attributes);
      if (lookahead == ']') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(47);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_verbatim_attributes);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_BSLASH_LBRACK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_BSLASH_RBRACK);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_BSLASH_LPAREN);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_BSLASH_RPAREN);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '$') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_DOLLAR_DOLLAR);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_math_content_bracket);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_math_content_bracket);
      if (lookahead == '\\') ADVANCE(31);
      if (lookahead != 0) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_math_content_paren);
      if (lookahead == '\\') ADVANCE(30);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'T') ADVANCE(68);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'X') ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'Z') ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Y') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'a') ADVANCE(61);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'a') ADVANCE(78);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'b') ADVANCE(41);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'e') ADVANCE(62);
      if (lookahead == 'i') ADVANCE(73);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'e') ADVANCE(62);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'e') ADVANCE(76);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'e') ADVANCE(79);
      if (lookahead == 'i') ADVANCE(74);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'e') ADVANCE(79);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'i') ADVANCE(75);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'k') ADVANCE(63);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'k') ADVANCE(80);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'm') ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'r') ADVANCE(66);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 't') ADVANCE(72);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 't') ADVANCE(71);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'x') ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == 'z') ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(81);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'L', 1,
        'T', 2,
        'V', 3,
        'j', 4,
        'l', 5,
        't', 6,
        'v', 7,
        'y', 8,
      );
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(10);
      if (lookahead == 'i') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(15);
      if (lookahead == 'i') ADVANCE(16);
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == 'T') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == 'X') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 'k') ADVANCE(22);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 15:
      if (lookahead == 'x') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'k') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'm') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 'm') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__tex_tag_name);
      END_STATE();
    case 22:
      if (lookahead == 'Z') ADVANCE(21);
      END_STATE();
    case 23:
      if (lookahead == 'b') ADVANCE(31);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 26:
      if (lookahead == 'z') ADVANCE(21);
      END_STATE();
    case 27:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 'b') ADVANCE(34);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 30:
      if (lookahead == 'X') ADVANCE(21);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__plain_tag_name);
      if (lookahead == 'a') ADVANCE(35);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_frontmatter_language);
      END_STATE();
    case 33:
      if (lookahead == 'x') ADVANCE(21);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__plain_tag_name);
      if (lookahead == 'a') ADVANCE(36);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 37:
      if (lookahead == 'i') ADVANCE(39);
      END_STATE();
    case 38:
      if (lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 39:
      if (lookahead == 'm') ADVANCE(41);
      END_STATE();
    case 40:
      if (lookahead == 'm') ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__plain_tag_name);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 32, .external_lex_state = 2},
  [2] = {.lex_state = 32, .external_lex_state = 3},
  [3] = {.lex_state = 32, .external_lex_state = 3},
  [4] = {.lex_state = 32, .external_lex_state = 3},
  [5] = {.lex_state = 32, .external_lex_state = 3},
  [6] = {.lex_state = 32, .external_lex_state = 3},
  [7] = {.lex_state = 32, .external_lex_state = 3},
  [8] = {.lex_state = 32, .external_lex_state = 3},
  [9] = {.lex_state = 32, .external_lex_state = 3},
  [10] = {.lex_state = 32, .external_lex_state = 3},
  [11] = {.lex_state = 32, .external_lex_state = 3},
  [12] = {.lex_state = 32, .external_lex_state = 3},
  [13] = {.lex_state = 32, .external_lex_state = 3},
  [14] = {.lex_state = 32, .external_lex_state = 3},
  [15] = {.lex_state = 32, .external_lex_state = 3},
  [16] = {.lex_state = 32, .external_lex_state = 3},
  [17] = {.lex_state = 32, .external_lex_state = 3},
  [18] = {.lex_state = 32, .external_lex_state = 3},
  [19] = {.lex_state = 32, .external_lex_state = 3},
  [20] = {.lex_state = 32, .external_lex_state = 3},
  [21] = {.lex_state = 32, .external_lex_state = 3},
  [22] = {.lex_state = 32, .external_lex_state = 3},
  [23] = {.lex_state = 32, .external_lex_state = 3},
  [24] = {.lex_state = 32, .external_lex_state = 3},
  [25] = {.lex_state = 32, .external_lex_state = 3},
  [26] = {.lex_state = 1, .external_lex_state = 4},
  [27] = {.lex_state = 32, .external_lex_state = 5},
  [28] = {.lex_state = 1, .external_lex_state = 6},
  [29] = {.lex_state = 1, .external_lex_state = 7},
  [30] = {.lex_state = 32, .external_lex_state = 8},
  [31] = {.lex_state = 32, .external_lex_state = 9},
  [32] = {.lex_state = 0, .external_lex_state = 5},
  [33] = {.lex_state = 32},
  [34] = {.lex_state = 10},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 11},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 32},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1, .external_lex_state = 7},
  [41] = {.lex_state = 1, .external_lex_state = 4},
  [42] = {.lex_state = 32},
  [43] = {.lex_state = 1, .external_lex_state = 7},
  [44] = {.lex_state = 1, .external_lex_state = 4},
  [45] = {.lex_state = 1, .external_lex_state = 6},
  [46] = {.lex_state = 32},
  [47] = {.lex_state = 32, .external_lex_state = 8},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 32},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0, .external_lex_state = 10},
  [54] = {.lex_state = 0, .external_lex_state = 10},
  [55] = {.lex_state = 0, .external_lex_state = 10},
  [56] = {.lex_state = 32},
  [57] = {.lex_state = 32},
  [58] = {.lex_state = 32},
  [59] = {.lex_state = 32},
  [60] = {.lex_state = 32},
  [61] = {.lex_state = 32},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 32},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__word] = ACTIONS(1),
    [sym_frontmatter_language] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [sym__tex_tag_name] = ACTIONS(1),
    [sym__plain_tag_name] = ACTIONS(1),
    [sym__verbatim_tag_name] = ACTIONS(1),
    [sym_verbatim_attributes] = ACTIONS(1),
    [anon_sym_BSLASH_LBRACK] = ACTIONS(1),
    [anon_sym_BSLASH_RBRACK] = ACTIONS(1),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(1),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_DOLLAR_DOLLAR] = ACTIONS(1),
    [sym_math_content_bracket] = ACTIONS(1),
    [sym_math_content_paren] = ACTIONS(1),
    [sym__frontmatter_start] = ACTIONS(1),
    [sym__frontmatter_end] = ACTIONS(1),
    [sym__frontmatter_body] = ACTIONS(1),
    [sym__verbatim_tex_content] = ACTIONS(1),
    [sym__verbatim_plain_content] = ACTIONS(1),
    [sym__inline_math_content] = ACTIONS(1),
    [sym__display_math_content] = ACTIONS(1),
    [sym__markdown_chunk] = ACTIONS(1),
    [sym__svelte_expression_body] = ACTIONS(1),
    [sym__error_sentinel] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(62),
    [sym_frontmatter] = STATE(3),
    [sym__block] = STATE(2),
    [sym_svelte_expression] = STATE(2),
    [sym_verbatim_environment] = STATE(2),
    [sym__verbatim_tex] = STATE(9),
    [sym__verbatim_plain] = STATE(7),
    [sym_verbatim_tex_open_tag] = STATE(26),
    [sym_verbatim_plain_open_tag] = STATE(29),
    [sym_display_math] = STATE(2),
    [sym_inline_math] = STATE(2),
    [sym__dollar] = STATE(28),
    [sym__dollar_dollar] = STATE(30),
    [sym_markdown_chunk] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_BSLASH_LBRACK] = ACTIONS(9),
    [anon_sym_BSLASH_LPAREN] = ACTIONS(11),
    [anon_sym_DOLLAR] = ACTIONS(13),
    [anon_sym_DOLLAR_DOLLAR] = ACTIONS(15),
    [sym__frontmatter_start] = ACTIONS(17),
    [sym__markdown_chunk] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_BSLASH_LBRACK,
    ACTIONS(11), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOLLAR,
    ACTIONS(15), 1,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(19), 1,
      sym__markdown_chunk,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym__verbatim_plain,
    STATE(9), 1,
      sym__verbatim_tex,
    STATE(26), 1,
      sym_verbatim_tex_open_tag,
    STATE(28), 1,
      sym__dollar,
    STATE(29), 1,
      sym_verbatim_plain_open_tag,
    STATE(30), 1,
      sym__dollar_dollar,
    STATE(4), 7,
      sym__block,
      sym_svelte_expression,
      sym_verbatim_environment,
      sym_display_math,
      sym_inline_math,
      sym_markdown_chunk,
      aux_sym_document_repeat1,
  [52] = 15,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_BSLASH_LBRACK,
    ACTIONS(11), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOLLAR,
    ACTIONS(15), 1,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(19), 1,
      sym__markdown_chunk,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym__verbatim_plain,
    STATE(9), 1,
      sym__verbatim_tex,
    STATE(26), 1,
      sym_verbatim_tex_open_tag,
    STATE(28), 1,
      sym__dollar,
    STATE(29), 1,
      sym_verbatim_plain_open_tag,
    STATE(30), 1,
      sym__dollar_dollar,
    STATE(5), 7,
      sym__block,
      sym_svelte_expression,
      sym_verbatim_environment,
      sym_display_math,
      sym_inline_math,
      sym_markdown_chunk,
      aux_sym_document_repeat1,
  [104] = 15,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(28), 1,
      anon_sym_LT,
    ACTIONS(31), 1,
      anon_sym_BSLASH_LBRACK,
    ACTIONS(34), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(37), 1,
      anon_sym_DOLLAR,
    ACTIONS(40), 1,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(43), 1,
      sym__markdown_chunk,
    STATE(7), 1,
      sym__verbatim_plain,
    STATE(9), 1,
      sym__verbatim_tex,
    STATE(26), 1,
      sym_verbatim_tex_open_tag,
    STATE(28), 1,
      sym__dollar,
    STATE(29), 1,
      sym_verbatim_plain_open_tag,
    STATE(30), 1,
      sym__dollar_dollar,
    STATE(4), 7,
      sym__block,
      sym_svelte_expression,
      sym_verbatim_environment,
      sym_display_math,
      sym_inline_math,
      sym_markdown_chunk,
      aux_sym_document_repeat1,
  [156] = 15,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_BSLASH_LBRACK,
    ACTIONS(11), 1,
      anon_sym_BSLASH_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOLLAR,
    ACTIONS(15), 1,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(19), 1,
      sym__markdown_chunk,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym__verbatim_plain,
    STATE(9), 1,
      sym__verbatim_tex,
    STATE(26), 1,
      sym_verbatim_tex_open_tag,
    STATE(28), 1,
      sym__dollar,
    STATE(29), 1,
      sym_verbatim_plain_open_tag,
    STATE(30), 1,
      sym__dollar_dollar,
    STATE(4), 7,
      sym__block,
      sym_svelte_expression,
      sym_verbatim_environment,
      sym_display_math,
      sym_inline_math,
      sym_markdown_chunk,
      aux_sym_document_repeat1,
  [208] = 2,
    ACTIONS(50), 1,
      anon_sym_DOLLAR,
    ACTIONS(48), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [221] = 2,
    ACTIONS(54), 1,
      anon_sym_DOLLAR,
    ACTIONS(52), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [234] = 2,
    ACTIONS(58), 1,
      anon_sym_DOLLAR,
    ACTIONS(56), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [247] = 2,
    ACTIONS(54), 1,
      anon_sym_DOLLAR,
    ACTIONS(52), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [260] = 2,
    ACTIONS(62), 1,
      anon_sym_DOLLAR,
    ACTIONS(60), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [273] = 2,
    ACTIONS(66), 1,
      anon_sym_DOLLAR,
    ACTIONS(64), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [286] = 2,
    ACTIONS(70), 1,
      anon_sym_DOLLAR,
    ACTIONS(68), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [299] = 2,
    ACTIONS(74), 1,
      anon_sym_DOLLAR,
    ACTIONS(72), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [312] = 2,
    ACTIONS(78), 1,
      anon_sym_DOLLAR,
    ACTIONS(76), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [325] = 2,
    ACTIONS(82), 1,
      anon_sym_DOLLAR,
    ACTIONS(80), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [338] = 2,
    ACTIONS(86), 1,
      anon_sym_DOLLAR,
    ACTIONS(84), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [351] = 2,
    ACTIONS(90), 1,
      anon_sym_DOLLAR,
    ACTIONS(88), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [364] = 2,
    ACTIONS(94), 1,
      anon_sym_DOLLAR,
    ACTIONS(92), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [377] = 2,
    ACTIONS(98), 1,
      anon_sym_DOLLAR,
    ACTIONS(96), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [390] = 2,
    ACTIONS(102), 1,
      anon_sym_DOLLAR,
    ACTIONS(100), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [403] = 2,
    ACTIONS(106), 1,
      anon_sym_DOLLAR,
    ACTIONS(104), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [416] = 2,
    ACTIONS(110), 1,
      anon_sym_DOLLAR,
    ACTIONS(108), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [429] = 2,
    ACTIONS(114), 1,
      anon_sym_DOLLAR,
    ACTIONS(112), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [442] = 2,
    ACTIONS(118), 1,
      anon_sym_DOLLAR,
    ACTIONS(116), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [455] = 2,
    ACTIONS(122), 1,
      anon_sym_DOLLAR,
    ACTIONS(120), 7,
      sym__markdown_chunk,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_BSLASH_LBRACK,
      anon_sym_BSLASH_LPAREN,
      anon_sym_DOLLAR_DOLLAR,
  [468] = 4,
    ACTIONS(124), 1,
      anon_sym_LT_SLASH,
    ACTIONS(126), 1,
      sym__verbatim_tex_content,
    STATE(12), 1,
      sym_verbatim_close_tag,
    STATE(37), 1,
      sym_tex_verbatim_body,
  [481] = 4,
    ACTIONS(128), 1,
      sym_frontmatter_language,
    ACTIONS(130), 1,
      sym__frontmatter_end,
    ACTIONS(132), 1,
      sym__frontmatter_body,
    STATE(55), 1,
      sym_frontmatter_content,
  [494] = 4,
    ACTIONS(134), 1,
      anon_sym_DOLLAR,
    ACTIONS(136), 1,
      sym__inline_math_content,
    STATE(14), 1,
      sym__dollar,
    STATE(35), 1,
      sym_math_content_inline,
  [507] = 4,
    ACTIONS(124), 1,
      anon_sym_LT_SLASH,
    ACTIONS(138), 1,
      sym__verbatim_plain_content,
    STATE(13), 1,
      sym_verbatim_close_tag,
    STATE(39), 1,
      sym_plain_verbatim_body,
  [520] = 4,
    ACTIONS(140), 1,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(142), 1,
      sym__display_math_content,
    STATE(11), 1,
      sym__dollar_dollar,
    STATE(38), 1,
      sym_math_content_display,
  [533] = 3,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
    ACTIONS(146), 1,
      sym__svelte_expression_body,
    STATE(58), 1,
      sym_svelte_expression_body,
  [543] = 3,
    ACTIONS(132), 1,
      sym__frontmatter_body,
    ACTIONS(148), 1,
      sym__frontmatter_end,
    STATE(54), 1,
      sym_frontmatter_content,
  [553] = 2,
    ACTIONS(150), 1,
      sym__tex_tag_name,
    ACTIONS(152), 1,
      sym__plain_tag_name,
  [560] = 2,
    ACTIONS(154), 1,
      anon_sym_BSLASH_RPAREN,
    ACTIONS(156), 1,
      sym_math_content_paren,
  [567] = 2,
    ACTIONS(134), 1,
      anon_sym_DOLLAR,
    STATE(19), 1,
      sym__dollar,
  [574] = 2,
    ACTIONS(158), 1,
      anon_sym_BSLASH_RBRACK,
    ACTIONS(160), 1,
      sym_math_content_bracket,
  [581] = 2,
    ACTIONS(124), 1,
      anon_sym_LT_SLASH,
    STATE(20), 1,
      sym_verbatim_close_tag,
  [588] = 2,
    ACTIONS(140), 1,
      anon_sym_DOLLAR_DOLLAR,
    STATE(18), 1,
      sym__dollar_dollar,
  [595] = 2,
    ACTIONS(124), 1,
      anon_sym_LT_SLASH,
    STATE(21), 1,
      sym_verbatim_close_tag,
  [602] = 1,
    ACTIONS(162), 2,
      sym__verbatim_plain_content,
      anon_sym_LT_SLASH,
  [607] = 1,
    ACTIONS(164), 2,
      sym__verbatim_tex_content,
      anon_sym_LT_SLASH,
  [612] = 2,
    ACTIONS(166), 1,
      anon_sym_GT,
    ACTIONS(168), 1,
      sym_verbatim_attributes,
  [619] = 1,
    ACTIONS(170), 2,
      sym__verbatim_plain_content,
      anon_sym_LT_SLASH,
  [624] = 1,
    ACTIONS(172), 2,
      sym__verbatim_tex_content,
      anon_sym_LT_SLASH,
  [629] = 1,
    ACTIONS(116), 2,
      sym__inline_math_content,
      anon_sym_DOLLAR,
  [634] = 2,
    ACTIONS(174), 1,
      anon_sym_GT,
    ACTIONS(176), 1,
      sym_verbatim_attributes,
  [641] = 1,
    ACTIONS(120), 2,
      sym__display_math_content,
      anon_sym_DOLLAR_DOLLAR,
  [646] = 1,
    ACTIONS(178), 1,
      anon_sym_LT_SLASH,
  [650] = 1,
    ACTIONS(180), 1,
      anon_sym_DOLLAR,
  [654] = 1,
    ACTIONS(182), 1,
      sym__verbatim_tag_name,
  [658] = 1,
    ACTIONS(184), 1,
      anon_sym_DOLLAR_DOLLAR,
  [662] = 1,
    ACTIONS(186), 1,
      anon_sym_LT_SLASH,
  [666] = 1,
    ACTIONS(188), 1,
      sym__frontmatter_end,
  [670] = 1,
    ACTIONS(190), 1,
      sym__frontmatter_end,
  [674] = 1,
    ACTIONS(192), 1,
      sym__frontmatter_end,
  [678] = 1,
    ACTIONS(194), 1,
      anon_sym_GT,
  [682] = 1,
    ACTIONS(196), 1,
      anon_sym_GT,
  [686] = 1,
    ACTIONS(198), 1,
      anon_sym_RBRACE,
  [690] = 1,
    ACTIONS(200), 1,
      anon_sym_GT,
  [694] = 1,
    ACTIONS(202), 1,
      anon_sym_RBRACE,
  [698] = 1,
    ACTIONS(204), 1,
      anon_sym_BSLASH_RBRACK,
  [702] = 1,
    ACTIONS(206), 1,
      ts_builtin_sym_end,
  [706] = 1,
    ACTIONS(208), 1,
      anon_sym_BSLASH_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 52,
  [SMALL_STATE(4)] = 104,
  [SMALL_STATE(5)] = 156,
  [SMALL_STATE(6)] = 208,
  [SMALL_STATE(7)] = 221,
  [SMALL_STATE(8)] = 234,
  [SMALL_STATE(9)] = 247,
  [SMALL_STATE(10)] = 260,
  [SMALL_STATE(11)] = 273,
  [SMALL_STATE(12)] = 286,
  [SMALL_STATE(13)] = 299,
  [SMALL_STATE(14)] = 312,
  [SMALL_STATE(15)] = 325,
  [SMALL_STATE(16)] = 338,
  [SMALL_STATE(17)] = 351,
  [SMALL_STATE(18)] = 364,
  [SMALL_STATE(19)] = 377,
  [SMALL_STATE(20)] = 390,
  [SMALL_STATE(21)] = 403,
  [SMALL_STATE(22)] = 416,
  [SMALL_STATE(23)] = 429,
  [SMALL_STATE(24)] = 442,
  [SMALL_STATE(25)] = 455,
  [SMALL_STATE(26)] = 468,
  [SMALL_STATE(27)] = 481,
  [SMALL_STATE(28)] = 494,
  [SMALL_STATE(29)] = 507,
  [SMALL_STATE(30)] = 520,
  [SMALL_STATE(31)] = 533,
  [SMALL_STATE(32)] = 543,
  [SMALL_STATE(33)] = 553,
  [SMALL_STATE(34)] = 560,
  [SMALL_STATE(35)] = 567,
  [SMALL_STATE(36)] = 574,
  [SMALL_STATE(37)] = 581,
  [SMALL_STATE(38)] = 588,
  [SMALL_STATE(39)] = 595,
  [SMALL_STATE(40)] = 602,
  [SMALL_STATE(41)] = 607,
  [SMALL_STATE(42)] = 612,
  [SMALL_STATE(43)] = 619,
  [SMALL_STATE(44)] = 624,
  [SMALL_STATE(45)] = 629,
  [SMALL_STATE(46)] = 634,
  [SMALL_STATE(47)] = 641,
  [SMALL_STATE(48)] = 646,
  [SMALL_STATE(49)] = 650,
  [SMALL_STATE(50)] = 654,
  [SMALL_STATE(51)] = 658,
  [SMALL_STATE(52)] = 662,
  [SMALL_STATE(53)] = 666,
  [SMALL_STATE(54)] = 670,
  [SMALL_STATE(55)] = 674,
  [SMALL_STATE(56)] = 678,
  [SMALL_STATE(57)] = 682,
  [SMALL_STATE(58)] = 686,
  [SMALL_STATE(59)] = 690,
  [SMALL_STATE(60)] = 694,
  [SMALL_STATE(61)] = 698,
  [SMALL_STATE(62)] = 702,
  [SMALL_STATE(63)] = 706,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_chunk, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_chunk, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_environment, 1, 0, 1),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_environment, 1, 0, 1),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 2, 0, 2),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_frontmatter, 2, 0, 2),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_svelte_expression, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_svelte_expression, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_display_math, 2, 2, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_display_math, 2, 2, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__verbatim_tex, 2, 0, 2),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__verbatim_tex, 2, 0, 2),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__verbatim_plain, 2, 0, 2),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__verbatim_plain, 2, 0, 2),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_math, 2, 1, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_math, 2, 1, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 3, 0, 3),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_frontmatter, 3, 0, 3),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 3, 0, 4),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_frontmatter, 3, 0, 4),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_svelte_expression, 3, 0, 5),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_svelte_expression, 3, 0, 5),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_display_math, 3, 2, 5),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_display_math, 3, 2, 5),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_math, 3, 1, 5),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_math, 3, 1, 5),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__verbatim_tex, 3, 0, 7),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__verbatim_tex, 3, 0, 7),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__verbatim_plain, 3, 0, 7),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__verbatim_plain, 3, 0, 7),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 4, 0, 8),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_frontmatter, 4, 0, 8),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_close_tag, 3, 0, 6),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_close_tag, 3, 0, 6),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__dollar, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__dollar, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__dollar_dollar, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__dollar_dollar, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_plain_open_tag, 4, 0, 9),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_tex_open_tag, 3, 0, 6),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_plain_open_tag, 3, 0, 6),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_tex_open_tag, 4, 0, 9),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tex_verbatim_body, 1, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_content_inline, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_content_display, 1, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plain_verbatim_body, 1, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter_content, 1, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_svelte_expression_body, 1, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [206] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__frontmatter_start = 0,
  ts_external_token__frontmatter_end = 1,
  ts_external_token__frontmatter_body = 2,
  ts_external_token__verbatim_tex_content = 3,
  ts_external_token__verbatim_plain_content = 4,
  ts_external_token__inline_math_content = 5,
  ts_external_token__display_math_content = 6,
  ts_external_token__markdown_chunk = 7,
  ts_external_token__svelte_expression_body = 8,
  ts_external_token__error_sentinel = 9,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__frontmatter_start] = sym__frontmatter_start,
  [ts_external_token__frontmatter_end] = sym__frontmatter_end,
  [ts_external_token__frontmatter_body] = sym__frontmatter_body,
  [ts_external_token__verbatim_tex_content] = sym__verbatim_tex_content,
  [ts_external_token__verbatim_plain_content] = sym__verbatim_plain_content,
  [ts_external_token__inline_math_content] = sym__inline_math_content,
  [ts_external_token__display_math_content] = sym__display_math_content,
  [ts_external_token__markdown_chunk] = sym__markdown_chunk,
  [ts_external_token__svelte_expression_body] = sym__svelte_expression_body,
  [ts_external_token__error_sentinel] = sym__error_sentinel,
};

static const bool ts_external_scanner_states[11][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__frontmatter_start] = true,
    [ts_external_token__frontmatter_end] = true,
    [ts_external_token__frontmatter_body] = true,
    [ts_external_token__verbatim_tex_content] = true,
    [ts_external_token__verbatim_plain_content] = true,
    [ts_external_token__inline_math_content] = true,
    [ts_external_token__display_math_content] = true,
    [ts_external_token__markdown_chunk] = true,
    [ts_external_token__svelte_expression_body] = true,
    [ts_external_token__error_sentinel] = true,
  },
  [2] = {
    [ts_external_token__frontmatter_start] = true,
    [ts_external_token__markdown_chunk] = true,
  },
  [3] = {
    [ts_external_token__markdown_chunk] = true,
  },
  [4] = {
    [ts_external_token__verbatim_tex_content] = true,
  },
  [5] = {
    [ts_external_token__frontmatter_end] = true,
    [ts_external_token__frontmatter_body] = true,
  },
  [6] = {
    [ts_external_token__inline_math_content] = true,
  },
  [7] = {
    [ts_external_token__verbatim_plain_content] = true,
  },
  [8] = {
    [ts_external_token__display_math_content] = true,
  },
  [9] = {
    [ts_external_token__svelte_expression_body] = true,
  },
  [10] = {
    [ts_external_token__frontmatter_end] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_sveltex_external_scanner_create(void);
void tree_sitter_sveltex_external_scanner_destroy(void *);
bool tree_sitter_sveltex_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_sveltex_external_scanner_serialize(void *, char *);
void tree_sitter_sveltex_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sveltex(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__word,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_sveltex_external_scanner_create,
      tree_sitter_sveltex_external_scanner_destroy,
      tree_sitter_sveltex_external_scanner_scan,
      tree_sitter_sveltex_external_scanner_serialize,
      tree_sitter_sveltex_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "sveltex",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
