import container from 'markdown-it-container';
import { defineConfig } from 'vitepress';
import { transformerTwoslash } from '@shikijs/vitepress-twoslash';
import { githubDarkDefault } from './theme/code-theme.js';

import markdownItMultimdTable from 'markdown-it-multimd-table';
import footnote from 'markdown-it-footnote';
import { readFile } from 'fs/promises';
import jsYaml from 'js-yaml';
import tailwindcss from '@tailwindcss/vite';

// The API sidebar is derived from `@nvl/sveltex`'s TSDoc at config-load time by
// `loadApi()` (cached on disk; see `scripts/api-data.mjs`) — the same source the
// `src/api/**/[id].paths.js` dynamic routes and `index.data.js` consume — so
// there's no generated sidebar file to import and keep in sync.
import { loadApi, PKG_SRC } from '../scripts/api-data.mjs';

/**
 * Reads a TextMate grammar from a YAML source file under
 * `packages/vscode-sveltex/syntaxes/`. The YAMLs are the hand-authored
 * source of truth (the JSON copies VS Code loads are pure build artifacts
 * regenerated by `scripts/build.ts`); read them here directly so the docs
 * site does not depend on the extension having been built.
 *
 * Typed `any` to match what the file-replaced `JSON.parse(await readFile(…))`
 * returned, which Shiki's `loadLanguage` (its `BundledLanguage |
 * LanguageInput | SpecialLanguage` parameter) accepts implicitly.
 */
async function loadTmGrammarYaml(path: string): Promise<any> {
    return jsYaml.load(await readFile(path, 'utf8'));
}

export const ESBUILD_MODULES_TARGET = [
    'es2022',
    // 'edge89',
    // 'firefox89',
    'chrome126',
    // 'safari15',
];

// https://vitepress.dev/reference/site-config
const { sidebar: apiSidebar } = await loadApi();

export default defineConfig({
    title: 'SvelTeX',
    description: 'Flexible Svelte preprocessor with extensive LaTeX support.',
    head: [['link', { rel: 'icon', type: 'image/png', href: '/favicon.png' }]],
    vite: {
        plugins: [
            tailwindcss() as any,
            // The API pages are derived from `@nvl/sveltex`'s source (via the
            // `src/api/**` loaders). That source sits outside the docs root, so
            // Vite's dev watcher ignores it by default; add it explicitly so
            // TSDoc edits live-regenerate the dynamic routes + index table.
            {
                name: 'sveltex-watch-api-source',
                configureServer(server) {
                    server.watcher.add(PKG_SRC);
                },
            },
        ],
        optimizeDeps: {
            exclude: ['@nvl/sveltex'],
            esbuildOptions: { target: ESBUILD_MODULES_TARGET },
        },
        esbuild: { target: ESBUILD_MODULES_TARGET },
        build: {
            rollupOptions: {
                // `@nvl/sveltex` is externalized (see `optimizeDeps.exclude`
                // above). `/playground/sveltex-playground.mjs` is the
                // pre-built SvelTeX browser bundle (emitted into
                // `src/public/` by `scripts/build-playground.mjs`); the
                // playground worker imports it from that runtime URL, so
                // Rollup must not try to resolve or bundle it.
                external: [
                    '@nvl/sveltex',
                    '/playground/sveltex-playground.mjs',
                ],
            },
            target: ESBUILD_MODULES_TARGET,
        },
        // The playground Web Worker (`theme/playground/worker.ts`) imports the
        // pre-built SvelTeX bundle from the runtime URL above; keep Rollup
        // from trying to resolve it when bundling the worker.
        worker: {
            rollupOptions: {
                external: ['/playground/sveltex-playground.mjs'],
            },
        },
    },
    markdown: {
        shikiSetup: async (shiki) => {
            const grammarSveltex = await loadTmGrammarYaml(
                '../packages/vscode-sveltex/syntaxes/sveltex.tmLanguage.yaml',
            );
            const grammarMarkdownForSveltex = await loadTmGrammarYaml(
                '../packages/vscode-sveltex/syntaxes/markdown.tmLanguage.yaml',
            );
            const grammarSvelte = JSON.parse(
                await readFile('misc/svelte.tmLanguage.json', 'utf8'),
            );
            grammarSveltex.name = 'sveltex';
            // Make our SvelTeX-flavored markdown grammar also answer to the
            // `md` shorthand used by `[md]` fences and by twoslash's hover-
            // popup renderer (Shiki v3 no longer auto-resolves common
            // aliases — VitePress 1 used to mask that).
            grammarMarkdownForSveltex.aliases = ['md'];
            await shiki.loadLanguage(
                grammarSvelte,
                grammarMarkdownForSveltex,
                grammarSveltex,
                // The sveltex grammar references `text.tex.latex` for the
                // body of `<tex>` / `<latex>` / `<tikz>` verbatim
                // environments; load Shiki's bundled LaTeX grammar so
                // that embedded scope resolves and `{A}` inside LaTeX
                // isn't mis-highlighted as a Svelte mustache tag.
                async () => (await import('shiki/langs/latex.mjs')).default,
                // VitePress 2 / shiki v3 dropped the implicit preload of
                // common languages — every grammar a code fence (or a
                // twoslash hover popup, or one of the SvelTeX grammar's
                // injections) refers to has to be loaded explicitly.
                //
                // - `html` / `ts` / `js` — used by
                //   `@shikijs/vitepress-twoslash`'s hover popups (and
                //   `html` is also the target of the sveltex grammar's
                //   `meta.embedded.block.html` injection).
                // - `sh` / `xml` — used by `[sh]` / `[xml]` fences on
                //   the docs pages.
                // - `css` / `scss` / `sass` / `postcss` / `stylus` —
                //   the sveltex grammar injects `<style lang="...">`
                //   blocks into these scopes.
                async () => (await import('shiki/langs/html.mjs')).default,
                async () => (await import('shiki/langs/ts.mjs')).default,
                async () => (await import('shiki/langs/js.mjs')).default,
                async () =>
                    (await import('shiki/langs/shellscript.mjs')).default,
                async () => (await import('shiki/langs/xml.mjs')).default,
                async () => (await import('shiki/langs/css.mjs')).default,
                async () => (await import('shiki/langs/scss.mjs')).default,
                async () => (await import('shiki/langs/sass.mjs')).default,
                async () => (await import('shiki/langs/postcss.mjs')).default,
                async () => (await import('shiki/langs/stylus.mjs')).default,
                // `yaml` — the sveltex grammar's frontmatter block embeds
                // `source.yaml`. Without it that include is unresolved, the
                // frontmatter isn't tokenized as YAML, and the math (`$…$`)
                // rule leaks into `$lib/...` import keys.
                async () => (await import('shiki/langs/yaml.mjs')).default,
            );
        },
        theme: {
            light: 'github-light-default',
            dark: githubDarkDefault,
        },
        math: true,
        codeTransformers: [transformerTwoslash() as any],
        config: (md) => {
            md.use(footnote as any);
            (md as any).use(markdownItMultimdTable, {
                autolabel: true,
                headerless: true,
                multibody: true,
                multiline: true,
                rowspan: true,
            });
            // Custom callouts: `::: info` / `::: tip` / `::: warning` /
            // `::: danger`. Override VitePress's built-in containers so all
            // four share one structure (`.custom-block` > `.custom-block-title`
            // + `.content`); the icon and inline-title layout are applied in
            // `theme/api.css`. The title defaults to the callout type and may
            // be overridden -- `::: warning Heads up` -- with inline markdown.
            const calloutTitle: Record<string, string> = {
                info: 'Info',
                tip: 'Tip',
                warning: 'Warning',
                danger: 'Danger',
            };
            for (const name of ['info', 'tip', 'warning', 'danger'] as const) {
                md.use(container as any, name, {
                    render: (tokens: any, idx: any) => {
                        const token = tokens[idx];
                        if (token.nesting !== 1) {
                            // Closing: end `.content`, then `.custom-block`.
                            return '</div></div>\n';
                        }
                        // `token.info` is the full `:::` params, e.g.
                        // "warning Heads up". Strip the type name to get an
                        // optional custom title; fall back to the default.
                        const custom = token.info
                            .trim()
                            .slice(name.length)
                            .trim();
                        const title = custom
                            ? md.renderInline(custom)
                            : calloutTitle[name];
                        return (
                            `<div class="custom-block ${name}">` +
                            '<div class="custom-block-title">' +
                            `<span class="custom-block-title-text">${title}</span>` +
                            '</div>' +
                            '<div class="content">'
                        );
                    },
                });
            }
        },
    },
    vue: {},
    appearance: {},

    themeConfig: {
        // https://vitepress.dev/reference/default-theme-config
        nav: [
            { text: 'Home', link: '/' },
            { text: 'Docs', link: '/docs' },
            { text: 'API', link: '/api/' },
            { text: 'Playground', link: '/docs/playground' },
        ],
        editLink: {
            pattern: 'https://github.com/nvlang/sveltex/edit/main/docs/:path',
            text: 'Suggest changes to this page',
        },
        darkModeSwitchLabel: 'Theme',
        lastUpdated: {
            formatOptions: {
                dateStyle: 'full',
            },
        },
        search: { provider: 'local' },
        notFound: {},
        logo: {
            light: '/logos/sveltex-light-monochrome.svg',
            dark: '/logos/sveltex-dark-monochrome.svg',
        },
        sidebar: {
            '/docs/': [
                {
                    text: 'Introduction',
                    base: '/docs',
                    collapsed: false,
                    items: [
                        { text: 'Overview', link: '/' },
                        { text: 'Getting Started', link: '/getting-started' },
                        { text: 'Playground', link: '/playground' },
                        { text: 'Acknowledgments', link: '/acknowledgments' },
                    ],
                },
                {
                    text: 'Usage',
                    base: '/docs',
                    collapsed: false,
                    items: [
                        { text: 'Markdown', link: '/markdown' },
                        { text: 'Code', link: '/code' },
                        { text: 'Math', link: '/math' },
                        { text: 'TeX', link: '/tex' },
                        { text: 'Verbatim', link: '/verbatim' },
                        {
                            text: 'Editor integration',
                            link: '/editor-integration',
                        },
                    ],
                },
                // {
                //     text: 'Examples',
                //     base: '/docs/examples',
                //     collapsed: false,
                //     items: [{ text: 'Basic', link: '/basic' }],
                // },
                {
                    text: 'Implementation',
                    base: '/docs/implementation',
                    collapsed: false,
                    items: [
                        { text: 'Escaping', link: '/escaping' },
                        { text: 'Markdown', link: '/markdown' },
                        { text: 'Testing', link: '/testing' },
                        {
                            text: 'TeX',
                            collapsed: false,
                            base: '/docs/implementation/tex',
                            items: [
                                { text: 'Overview', link: '/' },
                                {
                                    text: 'Compilation: TeX → DVI/PDF/XDV',
                                    link: '/compilation',
                                },
                                {
                                    text: 'Conversion: DVI → SVG',
                                    link: '/conversion',
                                },
                                {
                                    text: 'Optimization: SVG → Svelte',
                                    link: '/optimization',
                                },
                                { text: 'Caching', link: '/caching' },
                                { text: 'Benchmarks', link: '/benchmarks' },
                            ],
                        },
                    ],
                },
            ],
            // The API reference is generated into `src/api/` by
            // `scripts/build-api.mjs`; the sidebar (Overview + Interfaces +
            // Functions) comes from its `api-sidebar.json`.
            '/api/': apiSidebar,
        },

        socialLinks: [
            { icon: 'github', link: 'https://github.com/nvlang/sveltex' },
            { icon: 'npm', link: 'https://npmjs.com/package/@nvl/sveltex' },
            {
                icon: {
                    svg: '<svg role="img" style="scale: 1.4; margin-left: 10px;" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>JSR</title><path d="M3.692 5.538v3.693H0v7.384h7.385v1.847h12.923v-3.693H24V7.385h-7.385V5.538Zm1.846 1.847h1.847v7.384H1.846v-3.692h1.846v1.846h1.846zm3.693 0h5.538V9.23h-3.692v1.846h3.692v5.538H9.231V14.77h3.692v-1.846H9.231Zm7.384 1.846h5.539v3.692h-1.846v-1.846h-1.846v5.538h-1.847z"/></svg>',
                },
                link: 'https://jsr.io/@nvl/sveltex',
            },
        ],
    },
    lastUpdated: true,
    srcDir: 'src',
    cleanUrls: true,
    lang: 'en-US',
});
