---
name: Unit Tests (Vitest)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: read
  statuses: write

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-basic
            luatex
            xetex
            latexmk
            dvisvgm
            standalone
            pgf
            microtype
            mathtools
            luatex85
            lipsum
            xcolor

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: latest
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Install Poppler
        run: sudo apt-get install -y poppler-data poppler-utils

      - name: Install MuPDF
        run: sudo apt-get install -y mupdf mupdf-tools

      - name: Run Vitest tests
        run: pnpm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage/

      - name: Upload Vitest report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: vitest-report
          path: html/
          retention-days: 30
