---
name: Unit Tests (Vitest)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: read
  statuses: write

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Artifact Directory
        run: mkdir -p vitest-report

      - name: Run Unit Tests in Docker
        uses: addnab/docker-run-action@v3
        with:
          image: texlive/texlive:latest
          options: --volume ${{ github.workspace }}/vitest-report:/vitest-report
          run: |
            apt-get update
            apt-get install -y nodejs poppler-data poppler-utils
            node -v
            npm install -g pnpm
            pnpm install
            pnpm test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: vitest-report
          path: vitest-report/
          retention-days: 30
