---
name: Unit Tests 2 (Vitest)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: read
  statuses: write

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-basic
            luatex
            xetex
            latexmk
            dvisvgm
            standalone
            pgf
            microtype
            mathtools
            luatex85
            lipsum
            xcolor

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Poppler
        run: sudo apt-get install -y poppler-data poppler-utils

      - name: Install MuPDF
        run: sudo apt-get install -y mupdf mupdf-tools

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Run Vitest tests
        run: pnpm test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: vitest-report-2
          path: html/
          retention-days: 30
